docs_dir: docs
site_name: linux-rt-upscaler
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ src ]
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - Home: index.md
  - User Guide:
      - Installation: user/installation.md
      - Graphical User Interface (GUI): user/gui.md
      - Command-Line Interface (CLI): user/cli.md
      - Configuration: user/configuration.md
  - API Reference:
      - Session: api/session.md
      - Window Acquisition: api/acquisition.md
  - Developer:
      - Overview: developer/overview.md