docs_dir: docs
site_name: linux-rt-upscaler
repo_url: https://github.com/baronsmv/linux-rt-upscaler
repo_name: baronsmv/linux-rt-upscaler
site_description: A real-time SRCNN upscaler for any X-Window.
site_author: baronsmv
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ src ]
          options:
            heading_level: 2
            show_source: false
            show_root_heading: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - User Guide:
      - Installation: user/installation.md
      - Graphical User Interface (GUI): user/gui.md
      - Command-Line Interface (CLI): user/cli.md
      - Controls: user/controls.md
      - Configuration: user/configuration.md
  - API Reference:
      - API Overview: api/overview.md
      - Classes:
          - UpscalerSession: api/classes/upscaler_session.md
          - WindowInfo: api/classes/window_info.md
          - Config: api/classes/config.md
      - Modules:
          - Window Acquisition: api/modules/acquisition.md
          - Exceptions: api/modules/exceptions.md
  - Developer:
      - Overview: developer/overview.md
      - Architecture:
          - Architecture Limitations: developer/architecture/limitations.md